# Generated by Django 5.1.7 on 2025-04-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('FURNITURE', 'Furniture'), ('CLOTHING', 'Clothing'), ('FOOD', 'Food'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
