# Generated by Django 5.1.7 on 2025-04-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysettings',
            name='low_stock_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
