# Generated by Django 5.1.7 on 2025-04-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventorysettings_low_stock_notifications_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorysettings',
            name='low_stock_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
